apiVersion: v1
kind: Service
metadata:
  name: {{ include "consul.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "consul.name" . }}
    helm.sh/chart: {{ include "consul.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Values.namespace}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8500
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "consul.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
