# Default values for consul.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  enabled: true

domain: consul

namespace: apps
replicaCount: 1

image:
  repository: consul
  tag: 1.5.0
  pullPolicy: IfNotPresent

datacenter: dc1

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - consul-new.varu.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
volumes:
  name: data
persistentVolumeClaim:
  name: consul-claim
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  
## Persist data to persistent volume
# persistence:
#   enabled: true
storageClass: 
 
# Set StorageClass as the default StorageClass
  # Ignored if storageClass.create is false
  defaultClass: false

  # Set a StorageClass name
  # Ignored if storageClass.create is false
  name: nfs-client

  # Allow volume to be expanded dynamically
  allowVolumeExpansion: true

  # Method used to reclaim an obsoleted volume
  reclaimPolicy: Delete

  # When set to false your PVs will not be archived by the provisioner upon deletion of the PVC.
  archiveOnDelete: true

  storageClassName: nfs-client
  accessMode: ReadWriteMany
  size: 10Gi

client:
  enabled: "-"
  image: null
  join: null

connectInject:
  enabled: false
centralConfig:
  enabled: true
  defaultProtocol: null
  # proxyDefaults: |
  #     {}

nodeSelector: {}

tolerations: []

affinity: {}
# |
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#           matchLabels:
#             app: {{ template "consul.name" . }}
#             release: "{{ .Release.Name }}"
#             component: server
#       topologyKey: kubernetes.io/hostname
